- .gitignore
- Rare/Main.py
- Rare/MainWindow.py
- Rare/Tabs/GamesUninstalled/GameWidget.py
- Rare/utils/RareUtils.py
- Rare/utils/legendaryConfig.py
I was getting lots of errors when trying to start it without previously having set up legendary so I have fixed all the errors that I encountered.
> Fixed some errors

- rare/components/tab_utils.py
- rare/components/tab_widget.py
- start.sh
> add button to open epic games store in web browser

- rare/components/main_window.py
- rare/components/tabs/games/game_info/__init__.py
- rare/components/tabs/settings/rare.py
- rare/components/tabs/settings/settings_widget.py
- rare/languages/de.ts
Option to save window size after restart
> Save window size

- rare/components/tabs/downloads/__init__.py
- rare/components/tabs/downloads/download_thread.py
- rare/utils/models.py
- requirements.txt
Currently legendary does not handle stopping the download gracefully so we have to use some workarounds for now. I do not like it but until legendary gets updated there is not much choice on how to handle it. I have tested it on linux but it needs testing on windows.
> Add stop download button

- CONTRIBUTING.md
- rare/components/main_window.py
- rare/components/tab_widget.py
- rare/components/tabs/cloud_saves/__init__.py
- rare/components/tabs/downloads/__init__.py
- rare/components/tabs/games/game_info/__init__.py
- rare/components/tabs/games/game_info/game_settings.py
- rare/components/tabs/games/game_list.py
- rare/components/tabs/games/game_widgets/base_installed_widget.py
- rare/components/tabs/games/game_widgets/installed_list_widget.py
- rare/components/tabs/settings/__init__.py
- rare/components/tabs/settings/rare.py
- rare/components/tabs/settings/rpc_settings.py
- rare/utils/legendary_utils.py
- rare/utils/rpc.py
- Fixed many bugs
- Check for running games at startup
- Discord rpc settings
- Added some options
- Added context menu in game list
- refactoring
> Added some features

- rare/components/dialogs/install_dialog.py
- rare/components/dialogs/launch_dialog.py
- rare/components/tab_widget.py
- rare/components/tabs/games/__init__.py
- rare/components/tabs/games/game_info/__init__.py
- rare/components/tabs/games/game_info/dlcs.py
- rare/components/tabs/games/game_list.py
- rare/utils/utils.py
Added support for DLCs in game settings. I added a new tab, which appears, if dlcs are available
> Add support for DLCs

- rare/__main__.py
- rare/app.py
- rare/components/dialogs/launch_dialog.py
- rare/components/main_window.py
- rare/components/tab_widget.py
- rare/components/tabs/account/__init__.py
- rare/components/tabs/cloud_saves/sync_widget.py
- rare/components/tabs/games/__init__.py
- rare/components/tabs/games/game_list.py
- rare/components/tabs/games/game_widgets/base_installed_widget.py
- rare/components/tabs/games/game_widgets/installed_icon_widget.py
- rare/components/tabs/games/game_widgets/installed_list_widget.py
- rare/utils/utils.py
Added offline mode and --offline option to run without Login
> Offline Mode

- rare/__init__.py
- rare/components/tab_widget.py
- rare/components/tabs/downloads/__init__.py
- rare/components/tabs/games/__init__.py
- rare/components/tabs/games/game_info/__init__.py
- rare/components/tabs/games/game_list.py
- rare/components/tabs/games/game_widgets/base_installed_widget.py
- rare/components/tabs/games/game_widgets/installed_icon_widget.py
- rare/components/tabs/games/import_widget.py
Now it will not recretate all game widgets. Only add new widgets and remove old widgets.
it would be nice if someone could test it
> (WIP) Optimize Library reload

- README.md
dpkg doesn't manage depends I think?
> Change to apt instead of dpkg

- rare/components/dialogs/login/import_widget.py
> add import platform

- .github/workflows/release.yml
- .github/workflows/tests.yml
- rare/components/tabs/games/game_info/game_info.py
* [workflows] Clone through actions
* Delete verify thread after finish
> Minor changes

- .github/workflows/release.yml
- .github/workflows/tests.yml
- .gitignore
- .gitmodules
- AppImageBuilder.yml
- rare/__main__.py
- setup.py
Move submodule to rare/legendary and add it in sys.path
> Fix conflicts with already installed legendary

- rare/components/tabs/shop/shop_widget.py
This attemped solution fixes a crash bug in the Store tab of Rare.
> Fixed crash issue in Store tab (Fixes Dummerle/Rare#147)

- rare/components/tabs/games/game_utils.py
- rare/components/tray_icon.py
- rare/utils/meta.py
> Save last played time and add quick launch for tray icon

- rare/components/dialogs/install_dialog.py
- rare/components/tabs/games/__init__.py
- rare/components/tabs/games/game_info/game_info.py
- rare/components/tabs/games/game_info/uninstalled_info.py
- rare/components/tabs/games/game_widgets/base_installed_widget.py
- rare/components/tabs/games/game_widgets/base_uninstalled_widget.py
- rare/components/tabs/games/head_bar.py
- rare/utils/utils.py
This pr adds Unreal Engine and UE assets to Game List.
> Add Unreal Engine support

- rare/utils/utils.py
Schemes have no extension already :)
> Got color schemes working

- rare/__main__.py
- rare/app.py
- rare/components/dialogs/launch_dialog.py
- rare/components/dialogs/login/import_login.py
- rare/components/tabs/account/__init__.py
- rare/components/tabs/downloads/__init__.py
- rare/components/tabs/downloads/dl_queue_widget.py
- rare/components/tabs/downloads/download_thread.py
- rare/components/tabs/games/__init__.py
- rare/components/tabs/games/cloud_save_utils.py
- rare/components/tabs/games/game_info/game_settings.py
- rare/components/tabs/games/game_utils.py
- rare/components/tabs/games/game_widgets/base_installed_widget.py
- rare/components/tabs/games/game_widgets/installed_icon_widget.py
- rare/components/tabs/games/game_widgets/installed_list_widget.py
- rare/components/tabs/games/game_widgets/installing_game_widget.py
- rare/components/tabs/games/import_sync/egl_sync_group.py
- rare/components/tabs/games/import_sync/import_group.py
- rare/components/tabs/settings/about.py
- rare/components/tabs/settings/dxvk.py
- rare/components/tabs/settings/legendary.py
- rare/components/tabs/settings/rare.py
- rare/components/tabs/shop/game_info.py
- rare/components/tabs/shop/shop_api_core.py
- rare/components/tabs/shop/shop_widget.py
- rare/utils/legendary_utils.py
- rare/utils/rpc.py
- rare/utils/singleton.py
- rare/utils/steam_grades.py
- rare/utils/utils.py
This PR should fix inconsistency in a lot of strings. Wherever possible, f-strings are used.
However, in all tr functions, we need to use format(), since f-strings don't work there.
Don't merge yet, since I'm gonna push more commits, since I don't want to have everything in one commit.
> Unify strings formatting

- README.md
Some corrections in the README and cleanup.
> Some corrections and cleanup in README.md

- rare/components/tabs/games/game_widgets/base_installed_widget.py
This just checks if the game is not installed and then shows a message.
> Fix uninstall for third party launcher games

- rare/__main__.py
- rare/components/tabs/games/cloud_save_utils.py
- rare/components/tabs/games/game_utils.py
- rare/game_launch_helper/__init__.py
- rare/game_launch_helper/lgd_helper.py
- rare/game_launch_helper/message_models.py
- rare/utils/game_process_helper.py
- rare/utils/utils.py
Start games in a detached process and add communication between processes
> Add game helper to launch games in a detached process

- setup.py
supplements for https://github.com/Dummerle/Rare/commit/3ef6d120e3e85d6ad12e279b1158633d7edd9205
> bump legendary requirements in setup.py to 0.20.32

- rare/components/dialogs/launch_dialog.py
- rare/models/base_game.py
- rare/shared/rare_core.py
> RareCore: Detect if a game in saves is from another account.

- rare/components/dialogs/cloud_save_dialog.py
- rare/components/tabs/settings/game_settings.py
- rare/game_launch_helper/__init__.py
- rare/models/game.py
- rare/ui/components/tabs/games/game_info/sync_widget.py
- rare/ui/components/tabs/games/game_info/sync_widget.ui
Some other fixes
- Open cloud save dialog after playing a game, if no action set on start
> More fixes

- misc/ui2py.sh
- rare/components/tabs/games/game_widgets/game_widget.py
- rare/components/tabs/games/integrations/egl_sync_group.py
- rare/lgndr/core.py
- rare/shared/rare_core.py
* Forcibly disable automatic sync with  EGL and hide the option. The option to selectively sync games with EGL is still available.
* Dynamically load the cover images in the library when their respective widget becomes visible. Should greatly improve both startup performance and responsiveness.
> Usability fixes

- .github/workflows/job_cx-freeze-msi.yml
- .github/workflows/job_cx-freeze-zip.yml
- .github/workflows/snapshot.yml
Also revert cx-freeze to python 3.11
> Workflows: Add dependency on version step

- README.md
I assume that this repo was previously owned by `Dummerle`.
> chore: Use actual target repo URLs.

- rare/models/steam.py
> SteamShortcuts: do not quote executable and start dir

- rare/commands/launcher/cloud_sync_dialog.py
- rare/components/tabs/library/details/cloud_saves.py
- rare/components/tabs/library/integrations/ubisoft_group.py
- rare/components/tabs/library/widgets/game_widget.py
- rare/utils/steam_shortcuts.py
- CloudSaves: convert time to the local timezone when displaying
- SteamShortcuts: check is `loginusers.vdf` exists before opening it
- UbisoftGroup: stop loading widget when the worker finishes in every case
> Minor fixes in steam shortcuts, ubisoft integration and cloud saves

- .github/ISSUE_TEMPLATE/bug_report.md
> github: update issues template

- rare/components/tabs/downloads/thread.py
> DownloadThread: do not try to mark application as installed if 'Donwload only' is set

- .github/workflows/_job_publish.yml
- .github/workflows/_job_version.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- **workflows: set repo url for gh**
- **workflows: check input string in case of empty input**
> workflows: set repo url for gh

- .github/workflows/_job_version.yml
- rare/components/tabs/library/__init__.py
- rare/components/tabs/library/widgets/__init__.py
- **workflows: don't mark pre-release as latest**
- **workflows: explicitly mark as not latest**
- **Library: fix library filter and order resetting after search/install/uninstall**
> Library: fix library filter and order resetting after search/install/uninstall

- rare/components/tabs/settings/widgets/proton.py
- rare/shared/workers/wine_resolver.py
- rare/utils/compat/utils.py
- rare/utils/paths.py
- **WineResolver: Ensure proton prefix is initialized before operating on it**
> WineResolver: Ensure proton prefix is initialized before operating on it

- .github/workflows/_job_nuitka-windows.yml
- rare/utils/compat/steam.py
- **workflows: use windows-latest for nuitka job, pending the removal of windows-2019**
- **compat/steam: test if `compatmanager_layer_name` attr exists in the manifest when checking its value**
> compat/steam: test if compatmanager_layer_name attr exists in the manifest when checking its value

- Makefile
- docs/index.md
- misc/requirements-presence.in
- misc/requirements.in
This pull request introduces improvements to the build and installation process, updates the documentation for clarity and completeness, and revises dependency management for the project. The main changes include adding a comprehensive `Makefile` for automating build steps, reorganizing and expanding installation instructions in the documentation, and updating Python package requirements.
**Build and Dependency Management:**
* Added a new `Makefile` that automates virtual environment setup, dependency installation, UI compilation, wheel building, installation, and cleanup for the project. This streamlines development and packaging workflows.
* Updated `misc/requirements.in` to explicitly include build tools (`build`, `installer`, `ruff`) and ensured `pypresence` is listed in the main …
> Merge `requirements` and `requirements-dev`
