rare/resources/stylesheets/RareStyle/stylesheet.qss
Specify widget size in ex, not px.
Make QComboBox look like a button, and editable QComboBox like a QLineEdit.
Make disabled widgets more distinguishable.
=> RareStyle: Fix QGroupBox title for Linux and Windows

README.md
This adds an explicit notice about cloning with submodules to `README.md`. There have been several false-positive reports about the system-installed legendary being used when running from source, whose cause is the submodule not being cloned alongside with Rare.
Also includes a typo fix and an ordering mistake fix.
=> Clarify about submodules when running from source

rare/components/tabs/games/game_info/game_settings.py
This removes a leftover `+`, which made the function `proton_prefix_save` burst into flames as a lone `+` has no meaning on a `str`.
=> Remove leftover + from f-string refactor which breaks Proton settings saving

rare/components/tabs/games/game_info/game_info.py
Initially reported on Discord, Rare currently crashes when opening game info while that game is being verified. This PR is a simple `float` to `int` conversion in the progress value of the verification progress bar to address exactly that.
=> Fix crash upon opening game info while verifying

rare/__main__.py, rare/components/tabs/games/game_widgets/base_installed_widget.py, rare/components/tabs/settings/rare.py, rare/utils/legendary_utils.py, rare/utils/utils.py
This avoids issues such as one reported on Discord, where on Windows `Desktop` has been moved to a non-standard location, and so the traditional `~/Desktop` path failed. It also has the advantage of respecting `$XDG_DATA_HOME`.
At the time of writing the implementation is finished, but largely untested. Specifically, I'm unsure about various Windows scenarios and the AppImage. I'd be happy if someone else could test those two.
=> Use QStandardPaths everywhere instead of guessing desktop and applications path

rare/components/tabs/games/__init__.py, rare/components/tabs/games/game_utils.py, rare/components/tabs/games/game_widgets/base_installed_widget.py, rare/components/tabs/games/game_widgets/base_uninstalled_widget.py, rare/components/tabs/games/game_widgets/installed_icon_widget.py, rare/components/tabs/games/game_widgets/installed_list_widget.py, rare/components/tabs/games/game_widgets/installing_game_widget.py, rare/components/tabs/games/game_widgets/uninstalled_icon_widget.py, rare/components/tabs/games/game_widgets/uninstalled_list_widget.py, rare/utils/extra_widgets.py, rare/widgets/library_layout.py
Introduces the LibraryLayout from #196.
This layout distributes the available space in both horizontal sides and in-between the widgets.
Known issues: When searching for a game, it will re-align visible widgets, effectively centering the results.
This is because the search and grouping functions are interleaved. #196 handles it differently by adjusting
the opacity and re-ordering of the irrelevant widgets.
=> LibraryLayout from #196

rare/components/tabs/games/game_info/game_info.py
Fixes the issue with statvfs not available on windows by just using shutil.disk_usage.
Also changes the "Available space" text in the pop up for uniformity.
=> Small enhancements in moving game

rare/utils/legendary_utils.py
There was a second deletion of the game folder, which is unnecessary.
=> Don't double delete the game dir

README.md
Hi @rare_devs,
I have created this Pull Request because I have resolved this [request for a Chocolatey package](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1099) and now, we can install **rare** using [Chocolatey](https://community.chocolatey.org/packages/rare).
For now, only the latest version (`1.8.9`) is available on Chocolatey. When new versions will be released, they will, then, be added to the Chocolatey package for users to enjoy. :slightly_smiling_face:
=>  Adds the Chocolatey package as a way to install Rare

.github/workflows/release-tests.yml, .github/workflows/release.yml, pyproject.toml, rare/components/dialogs/install_dialog.py, rare/components/tabs/downloads/download_thread.py, rare/game_launch_helper/__init__.py, rare/lgndr/cli.py, rare/lgndr/core.py
The division by zero error in `validate_files` was fixed in Legendary `0.20.29`, which also contains the reworked `get_cdn_manifest`, so that was removed too.
=> Lgndr: Update to legendary 0.20.29

misc/rare.desktop
The `Games` and `Multimedia` categories don't exist https://specifications.freedesktop.org/menu-spec/latest/apa.html
=> rare.desktop: fix categories

rare/shared/image_manager.py, rare/utils/paths.py
Before creating icons, check if desktop links are supported by Rare on the current platform.
Fixes Dummerle/Rare#262
=> ImageManager: Check if desktop icons are supported on current plaform

rare/shared/rare_core.py, rare/shared/workers/fetch.py
https://discord.com/channels/826881530310819914/884510635642216499/1111321692703305729
There is a tab character in the appId of Fallout New Vegas: Honest Hearts DLC, this breaks metadata storage on Windows as they can't handle tabs at the end of the filename (?).
Legendary and Heroic are also affected, but it completed breaks Rare, so dodge it for now pending a fix.
=> RareCore: Handle exception when fetching non-asset games

README.md, pyproject.toml, rare/utils/paths.py, requirements-full.txt, requirements-webview.txt, setup.py
This PR will add full FreeBSD support to Rare
=> feat: add freebsd support

pyproject.toml, setup.py
Looks like setup.py and pyproject.toml have not been updated to support legendary 0.20.33. This should fix compilation for those still using setup.py and fix the install test in .rpm packages that checks for dependencies and says unmet dependencies by missing legendary-gl = 0.20.32
Patch tested by myself on OpenMandriva Cooker: https://github.com/OpenMandrivaAssociation/rare/commit/336e7510a173deed4ede1284d46280100f8b98da
=> legendary 0.20.33 - fix missing bits

rare/utils/paths.py
Fixes launching the game launcher when Rare is installed through `pip` on Windows.
Fixes: #339
=> Paths: Apply the executable rename in `pythonw` too

rare/utils/compat/utils.py
When unsetting DISPLAY, Wine hangs after executing a command, and doesn't allow for other instances of wine to start, i.e. games do not launch, with a cryptic error. This also fixes the previously observed issues with `winepath.exe` and `reg.exe` never exiting.
This is likely due to the newly introduced Wayland driver. This behavior can be observed when Wayland support is compiled into Wine and the wayland driver is enabled in the prefix's registry. In this case, if running under X11 and DISPLAY is not set, Wine will hang, and the process never returns.
=> WineResolver: Do not unset 'DISPLAY' when running silently

rare/components/main_window.py, rare/components/tabs/games/game_widgets/game_widget.py, rare/widgets/loading_widget.py
Fixes a subtle bug that would cause increased CPU usage due to spawning multiple singleshot times with very short timeouts (15ms) until the Store tab was loaded.
=> LoadingWidget: Start playing movie once the widget is visible if `autostart` is enabled

rare/models/steam.py, rare/utils/steam_shortcuts.py
based on timestamp if the `MostRecent` field does not exist.
=> SteamShortcuts: fall back to determining the last logged-in Steam user

rare/models/base_game.py
If there aren't any saves for the game on the cloud, the game's saves list
is empty, and the first check failed. As a result the method would
erroneously report that there aren't any save games. This caused the
upload/download button in the cloud saves dialog and widget would be
disabled.
Fix it by removing the check and creating a fake save to satisfy
`check_savegame_state`
=> RareGameSlim: fix uploading save games when there aren't any on the remote

.github/workflows/job_cx-freeze-msi.yml, .github/workflows/job_cx-freeze-zip.yml, .github/workflows/job_macos.yml, .github/workflows/job_nuitka-win.yml, rare/commands/launcher/__init__.py, rare/commands/launcher/lgd_helper.py, rare/components/tabs/settings/widgets/launch.py, rare/utils/config_helper.py, rare/widgets/indicator_edit.py, requirements-dev.txt, requirements-full.txt, requirements.txt
- RareLauncher: fix cloud sync dialog not opening on pyside6 and blocking execution
- workflows: remove pywebview from packages
- RareLauncher: check before deleting CloudSyncDialog
- PathEdit: remove implicit use of shlex
- LaunchSettings: separate command input widget from the arguments widget
- project: update requirements.txt
=> Fix issues with rare's process launcher

.github/workflows/job_cx-freeze-appimage.yml, .github/workflows/job_cx-freeze-dmg.yml, .github/workflows/job_cx-freeze-msi.yml, .github/workflows/job_nuitka-linux.yml, .github/workflows/job_nuitka-macos.yml, .github/workflows/job_nuitka-windows.yml, .github/workflows/job_pypi.yml, .github/workflows/job_version.yml, .github/workflows/release.yml, .github/workflows/snapshot.yml, pyproject.toml
- **workflows: set `fetch-tags` to true**
- **workflows: describe version for release**
- **workflows: use SETUPTOOLS_SCM_PRETEND_VERSION= to work-around GH Actions issues**
- **Release 1.11.2 (Boga Discus) (Hotfix 2)**
=> Work-around versioning issues due to GH actions

rare/components/tabs/library/__init__.py, rare/components/tabs/library/details/cloud_saves.py, rare/components/tabs/library/details/details.py, rare/components/tabs/library/head_bar.py, rare/components/tabs/library/widgets/__init__.py, rare/models/game.py, rare/models/library.py, rare/models/signals.py, rare/shared/rare_core.py, rare/ui/components/tabs/library/details/details.py, rare/ui/components/tabs/library/details/details.ui
Implment the settings for tags. Add option to show hidden games in the filter options #278
Also fix #301
=> Add settings for tags

.github/workflows/_job_cx-freeze-appimage.yml, .github/workflows/_job_cx-freeze-dmg.yml, .github/workflows/_job_cx-freeze-msi.yml, README.md, misc/requirements-dev.in, pyproject.toml, setup.py
Using `pip install .` or `python -m build` fails if this directive it
present. Both of these commands work correctly without the directive by
using a barebones `setup.py`.
On the other hand, removing this directive breaks
`python3 -m setuptools_scm --force-write-version-files` which is used
in the workflows to generate `rare/_version.py` before packaging. In the
case of the workflows though we already override the version using
`SETUPTOOLS_SCM_PRETEND_VERSION` so it shouldn't be an issue.
=> chore: remove `version_scheme` from `pyproject.toml`
